baseURL = "https://beige-sweatshirt.github.io/"
languageCode = 'en-us'
title = 'Matt Holford'
enableRobotsTXT = false
sectionPagesMenu = "main"

[menu]
[[menu.main]]
  pageRef="/"
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef='projects'
  identifier="projects"
  name = 'Projects' 
  url = '/portfolio/projects/'
  weight = 20
[[menu.main]]
  pageRef = "contact"
  name = 'Contact'
  url = '/portfolio/contact/'
  weight = 30